In [ ]:
import h5py
import pandas as pd
from google.colab import drive
import numpy as np
drive.mount('/content/drive')
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

Mounted at /content/drive


In [ ]:
folder_path = '/content/drive/MyDrive/Power_flow_data'

In [ ]:
import pandas as pd
import os

def concatenate_csv_files_in_folder(folder_path):
    # Create an empty DataFrame
    concatenated_df = pd.DataFrame()

    # Loop through all files in the folder
    for filename in os.listdir(folder_path):
        # Check if the file is a CSV
        if filename.endswith('.csv'):
            file_path = os.path.join(folder_path, filename)
            # Read the CSV file and concatenate it to the DataFrame
            df = pd.read_csv(file_path)
            concatenated_df = pd.concat([concatenated_df, df], ignore_index=True)

    return concatenated_df

# Replace with your actual folder path
#folder_path = 'your_actual_path_to_folder_with_csv_files'
final_dataframe = concatenate_csv_files_in_folder(folder_path)
print(final_dataframe.head()) # Display the first few rows of the final DataFrame


             Timestamp DayOfWeek  PowerLineID  PowerFlowValue
0  2010-07-01 18:05:00  Thursday         1815          -26.00
1  2010-07-01 18:05:00  Thursday         1687          148.54
2  2010-07-01 18:05:00  Thursday         1567          -38.46
3  2010-07-01 18:05:00  Thursday          733           35.51
4  2010-07-01 18:05:00  Thursday         1688         -136.75


In [ ]:
output_file_path = '/content/drive/MyDrive/Power_flow_data/Data_Merged.csv'

# Save the DataFrame to a CSV file
final_dataframe.to_csv(output_file_path, index=False) # Set index=False if you don't want to save the index in the CSV

print(f"DataFrame saved to {output_file_path}")

DataFrame saved to /content/drive/MyDrive/Power_flow_data/Data_Merged.csv


In [ ]:
file_path = '/content/drive/MyDrive/2018_power_flow_data/adapt/X2.h5'

In [ ]:
h5_file = h5py.File(file_path, 'r')

# List all groups and datasets within the file
def print_hdf5_items(name, obj):
    if isinstance(obj, h5py.Group):
        print(f"Group: {name}")
    if isinstance(obj, h5py.Dataset):
        print(f"Dataset: {name}")

h5_file.visititems(print_hdf5_items)
h5_file.close()

Group: X
Dataset: X/type
Group: X/value
Group: X/value/X
Dataset: X/value/X/type
Dataset: X/value/X/value
Group: X/value/aux
Dataset: X/value/aux/type
Dataset: X/value/aux/value
Group: X/value/hat
Dataset: X/value/hat/type
Group: X/value/hat/value
Group: X/value/hat/value/X
Dataset: X/value/hat/value/X/type
Dataset: X/value/hat/value/X/value
Group: X/value/hat/value/t
Dataset: X/value/hat/value/t/type
Dataset: X/value/hat/value/t/value
Group: X/value/metadata
Dataset: X/value/metadata/type
Dataset: X/value/metadata/value
Group: X/value/t
Dataset: X/value/t/type
Dataset: X/value/t/value


In [ ]:
# Open the HDF5 file
h5_file = h5py.File('/content/drive/MyDrive/2018_power_flow_data/adapt/X1.h5','r')

# Access the first dataset ("X/type")
first_dataset = h5_file['X/value/X/value']
# Inspect the dataset properties
print("Dataset Name:", first_dataset.name)
print("Dataset Shape:", first_dataset.shape)
print("Dataset Data Type:", first_dataset.dtype)
print("Dataset Chunk Size:", first_dataset.chunks)  # Only available if the dataset is chunked

# Retrieve the data from the dataset
data = first_dataset[()]
print("Data Preview:")
print(data[:10])  # Display the first 10 elements, adjust as needed

# Close the file when you're done
h5_file.close()


Dataset Name: /X/value/X/value
Dataset Shape: (12, 1916, 1)
Dataset Data Type: float32
Dataset Chunk Size: None
Data Preview:
[[[354.97]
  [-52.18]
  [  0.  ]
  ...
  [  0.  ]
  [  0.  ]
  [  0.  ]]

 [[384.86]
  [-39.87]
  [  0.  ]
  ...
  [  0.  ]
  [  0.  ]
  [  0.  ]]

 [[382.49]
  [-36.12]
  [  0.  ]
  ...
  [  0.  ]
  [  0.  ]
  [  0.  ]]

 ...

 [[378.38]
  [-41.71]
  [  0.  ]
  ...
  [  0.  ]
  [  0.  ]
  [  0.  ]]

 [[371.61]
  [-40.53]
  [  0.  ]
  ...
  [  0.  ]
  [  0.  ]
  [  0.  ]]

 [[351.87]
  [-49.37]
  [  0.  ]
  ...
  [  0.  ]
  [  0.  ]
  [  0.  ]]]


# New Section

In [ ]:
import h5py
import os

# Set the directory where your .h5 files are located
directory = '/content/drive/My Drive/2018_power_flow_data/adapt'

# The expected shape
expected_shape = (12, 1916, 1)

# List to hold the names of files that do not match the expected shape
files_with_different_shape = []

# Loop through each file in the directory
for filename in os.listdir(directory):
    if filename.endswith(".h5"):  # Check only .h5 files
        file_path = os.path.join(directory, filename)
        with h5py.File(file_path, 'r') as h5_file:
            # Access the dataset
            dataset = h5_file['X/value/X/value']
            # Check the shape of the dataset
            if dataset.shape != expected_shape:
                files_with_different_shape.append(filename)
                print(f"File {filename} has a different shape: {dataset.shape}")

# Check if any files had a different shape
if files_with_different_shape:
    print("The following files have a different shape than expected:")
    for fname in files_with_different_shape:
        print(fname)
else:
    print("All files have the expected shape.")


File X5.h5 has a different shape: (164, 1916, 1)
File X2.h5 has a different shape: (1317, 1916, 1)
File X17.h5 has a different shape: (1120, 1916, 1)
File X38.h5 has a different shape: (2604, 1916, 1)
File X35.h5 has a different shape: (258, 1916, 1)
File X62.h5 has a different shape: (872, 1916, 1)
File X23.h5 has a different shape: (1480, 1916, 1)
File X50.h5 has a different shape: (280, 1916, 1)
File X8.h5 has a different shape: (557, 1916, 1)
File X68.h5 has a different shape: (1883, 1916, 1)
File X44.h5 has a different shape: (483, 1916, 1)
File X59.h5 has a different shape: (315, 1916, 1)
File X32.h5 has a different shape: (3023, 1916, 1)
File X47.h5 has a different shape: (894, 1916, 1)
File X65.h5 has a different shape: (2059, 1916, 1)
File X14.h5 has a different shape: (2127, 1916, 1)
File X26.h5 has a different shape: (140, 1916, 1)
File X41.h5 has a different shape: (673, 1916, 1)
File X11.h5 has a different shape: (904, 1916, 1)
File X29.h5 has a different shape: (806, 1916

In [ ]:
import pytz

# Example Unix timestamp
unix_timestamp = 1.247e+9

# Convert to datetime
human_readable_date = pd.to_datetime(unix_timestamp, unit='s',utc=True)

print(human_readable_date)

2009-07-07 20:53:20+00:00


In [ ]:
# Example Unix timestamp
unix_timestamp = 1.278e+9

# Convert to UTC datetime
utc_datetime = pd.to_datetime(unix_timestamp, unit='s', utc=True)

# Convert from UTC to the specified time zone
# Replace 'GOSAT' with the actual time zone name
timezone = 'EST'
localized_datetime = utc_datetime.tz_convert(timezone)

print(localized_datetime)

2010-07-01 11:00:00-05:00


In [ ]:
# Load HDF5 file
with h5py.File(file_path, 'r') as file:
    # Access the datasets
    records = file['X/value/X/value'][:]
    timestamps = file['X/value/t/value'][:]
    print("Raw Timestamps Sample:", timestamps.flatten()[:5])  # Prints the first 10 raw timestamps
    # Convert timestamps to datetime
    timestamps_converted = pd.to_datetime(timestamps.flatten(), unit='s')

    # Reshape the records array to align with timestamps
    records_reshaped = records.reshape(-1, records.shape[1])  # (number_of_timestamps, number_of_power_lines)

    # Create DataFrame for each power line's record with timestamps
    list_dfs = []
    for i in range(records_reshaped.shape[1]):  # iterate over power lines
        df_power_line = pd.DataFrame({
            'Timestamp': timestamps_converted,
            'PowerLineID': i,
            'PowerFlowValue': records_reshaped[:, i]
        })
        list_dfs.append(df_power_line)

    # Combine all individual DataFrames into one
    df_merged = pd.concat(list_dfs, ignore_index=True)

    # Filter for PowerLineID = 0
    df_filtered = df_merged[df_merged['PowerLineID'] == 3]

# Display the filtered DataFrame
print(df_filtered)
#df_filtered[(df_filtered['Timestamp'] >= '2010-07-02 00:00:00') & (df_filtered['Timestamp'] < '2010-07-03 00:00:00')]

Raw Timestamps Sample: [1.2780075e+09 1.2780078e+09 1.2780081e+09 1.2780084e+09 1.2780087e+09]
             Timestamp  PowerLineID  PowerFlowValue
36 2010-07-01 18:05:00            3      504.899994
37 2010-07-01 18:10:00            3      465.290009
38 2010-07-01 18:15:00            3      481.130005
39 2010-07-01 18:20:00            3      490.679993
40 2010-07-01 18:25:00            3      487.970001
41 2010-07-01 18:30:00            3      477.600006
42 2010-07-01 18:35:00            3      485.829987
43 2010-07-01 18:40:00            3      462.010010
44 2010-07-01 18:45:00            3      460.100006
45 2010-07-01 18:50:00            3      459.079987
46 2010-07-01 18:55:00            3      434.109985
47 2010-07-01 19:00:00            3      505.690002


In [ ]:
import h5py
import pandas as pd
import glob

# Define the path to the folder containing the HDF5 files
folder_path = '/content/drive/MyDrive/2018_power_flow_data/adapt/*.h5'  # Update this with your folder path
# List to store DataFrames from each file
all_dfs = []

# Iterate over each file in the folder
for file_path in glob.glob(folder_path):
    with h5py.File(file_path, 'r') as file:
        # Access the datasets
        records = file['X/value/X/value'][:]
        timestamps = file['X/value/t/value'][:]

        # Convert timestamps to datetime
        timestamps_converted = pd.to_datetime(timestamps.flatten(), unit='s')
        # Get the day of the week for each timestamp
        day_of_week = timestamps_converted.day_name()

        # Reshape the records array to align with timestamps
        records_reshaped = records.reshape(-1, records.shape[1])

        # Create DataFrame for each power line's record with timestamps
        list_dfs = []
        for i in range(records_reshaped.shape[1]):
            df_power_line = pd.DataFrame({
                'Timestamp': timestamps_converted,
                #'DayOfWeek': day_of_week,  # Add the day of the week here
                'PowerLineID': i,
                'PowerFlowValue': records_reshaped[:, i]
            })
            list_dfs.append(df_power_line)

        # Combine all individual DataFrames into one and append to the main list
        df_merged = pd.concat(list_dfs, ignore_index=True)
        all_dfs.append(df_merged)

# Concatenate all DataFrames from all files
df_combined = pd.concat(all_dfs, ignore_index=True)

# Sort the combined DataFrame by the 'Timestamp' column
df_combined_sorted = df_combined.sort_values(by='Timestamp')

# Optionally, filter for a specific PowerLineID (e.g., ID = 3)
#df_filtered = df_combined_sorted[df_combined_sorted['PowerLineID'] == 125]

print(df_combined_sorted)


                   Timestamp  PowerLineID  PowerFlowValue
47540892 2010-07-01 18:05:00          890       46.900002
47548908 2010-07-01 18:05:00         1558        0.000000
47551452 2010-07-01 18:05:00         1770      -41.330002
47530356 2010-07-01 18:05:00           12      594.729980
47534460 2010-07-01 18:05:00          354     -150.630005
...                      ...          ...             ...
33160093 2010-09-25 22:15:00          409       92.970001
32986857 2010-09-25 22:15:00          317     -176.279999
32909654 2010-09-25 22:15:00          276       56.799999
34278595 2010-09-25 22:15:00         1003      143.960007
33559289 2010-09-25 22:15:00          621       -5.440000

[47553204 rows x 3 columns]


In [ ]:
pivoted_combined_df = df_combined_sorted.pivot(index='Timestamp', columns='PowerLineID', values='PowerFlowValue')
print(pivoted_combined_df)

PowerLineID                0           1           2           3     \
Timestamp                                                             
2010-07-01 18:05:00  342.600006  -72.300003    0.000000  504.899994   
2010-07-01 18:10:00  340.519989  -77.459999    0.000000  465.290009   
2010-07-01 18:15:00  332.220001  -84.269997    0.000000  481.130005   
2010-07-01 18:20:00  323.000000  -74.360001    0.000000  490.679993   
2010-07-01 18:25:00  302.429993  -88.839996    0.000000  487.970001   
...                         ...         ...         ...         ...   
2010-09-25 21:55:00  202.080002  -73.230003  362.640015  388.920013   
2010-09-25 22:00:00  197.369995  -79.260002  371.399994  337.790009   
2010-09-25 22:05:00  154.869995 -112.800003  383.239990  262.529999   
2010-09-25 22:10:00  106.629997 -137.350006  382.660004  225.199997   
2010-09-25 22:15:00  116.470001 -120.360001  389.750000  235.820007   

PowerLineID                4           5           6           7     \
Times

In [ ]:
import h5py
import pandas as pd
import glob

# Define the path to the folder containing the HDF5 files
folder_path = '/content/drive/MyDrive/2018_power_flow_data/adapt/*.h5'  # Update this with your folder path
# List to store DataFrames from each file
all_dfs = []

# Iterate over each file in the folder
for file_path in glob.glob(folder_path):
    with h5py.File(file_path, 'r') as file:
        # Access the datasets
        records = file['X/value/X/value'][:]
        timestamps = file['X/value/t/value'][:]

        # Convert timestamps to datetime
        timestamps_converted = pd.to_datetime(timestamps.flatten(), unit='s')

        # Reshape the records array to align with timestamps
        records_reshaped = records.reshape(-1, records.shape[1])

        # Create DataFrame for each power line's record with timestamps
        list_dfs = []
        for i in range(records_reshaped.shape[1]):
            df_power_line = pd.DataFrame({
                'Timestamp': timestamps_converted,
                'PowerLineID': i,
                'PowerFlowValue': records_reshaped[:, i]
            })
            list_dfs.append(df_power_line)

        # Combine all individual DataFrames into one and append to the main list
        df_merged = pd.concat(list_dfs, ignore_index=True)
        all_dfs.append(df_merged)

# Concatenate all DataFrames from all files
df_combined = pd.concat(all_dfs, ignore_index=True)

# Sort the combined DataFrame by the 'Timestamp' column
df_combined_sorted = df_combined.sort_values(by='Timestamp')

# Round down the 'Timestamp' to the nearest hour and group by 'PowerLineID' and 'Timestamp'
df_combined_sorted['Timestamp'] = df_combined_sorted['Timestamp'].dt.floor('H')
df_hourly_avg = df_combined_sorted.groupby(['PowerLineID', 'Timestamp']).mean().reset_index()

print(df_hourly_avg)


         PowerLineID           Timestamp  PowerFlowValue
0                  0 2010-07-01 18:00:00      306.371826
1                  0 2010-07-01 19:00:00      367.140015
2                  0 2010-07-01 20:00:00      363.129150
3                  0 2010-07-01 21:00:00      480.254150
4                  0 2010-07-01 22:00:00      416.828339
...              ...                 ...             ...
3964199         1915 2010-09-25 18:00:00        0.000000
3964200         1915 2010-09-25 19:00:00        0.000000
3964201         1915 2010-09-25 20:00:00        0.000000
3964202         1915 2010-09-25 21:00:00        0.000000
3964203         1915 2010-09-25 22:00:00        0.000000

[3964204 rows x 3 columns]


In [ ]:
pivoted_df = df_hourly_avg.pivot(index='Timestamp', columns='PowerLineID', values='PowerFlowValue')
print(pivoted_df)

PowerLineID                0           1           2           3     \
Timestamp                                                             
2010-07-01 18:00:00  306.371826  -89.693634    0.000000  473.518188   
2010-07-01 19:00:00  367.140015  -45.134167    0.000000  592.751648   
2010-07-01 20:00:00  363.129150  -34.750835    0.000000  608.714172   
2010-07-01 21:00:00  480.254150   66.106667    0.000000  719.851624   
2010-07-01 22:00:00  416.828339    7.810833    0.000000  566.283325   
...                         ...         ...         ...         ...   
2010-09-25 18:00:00  217.884171   -0.980000  316.674164  492.391632   
2010-09-25 19:00:00  156.638336  -74.539162  283.223328  386.578339   
2010-09-25 20:00:00  151.856674 -112.578331  317.991669  319.893341   
2010-09-25 21:00:00  182.394165  -85.529999  355.242523  359.865845   
2010-09-25 22:00:00  143.834991 -112.442505  381.762512  265.334991   

PowerLineID                4           5            6           7     \
Time

In [ ]:
import os

# Assuming df_combined_sorted is your sorted DataFrame
# Create a directory for the CSV files if it doesn't exist
output_dir = '/content/drive/MyDrive/Power_flow_data_hourly'  # Update this with your desired path
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Group the DataFrame by the date part of the index
grouped = df_combined_sorted.groupby(df_combined_sorted['Timestamp'].dt.date)

# Iterate over each group, reset the index, and save to a separate CSV file
for date, group in grouped:
    group = group.reset_index()  # Reset the index to turn it into a column
    file_name = f'{date}.csv'
    file_path = os.path.join(output_dir, file_name)
    group.to_csv(file_path, index=False)

In [ ]:
print(grouped)